version: 2.1
executors:
  default-executor:
    docker:
      - image: circleci/node:lts
jobs:
  install-dependencies:
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies
      - run:
          name: "Install dependencies"
          command: yarn install && npm rebuild
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths: .

  check-prettier:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Check prettier"
          command: echo 'Fake prettier check'

  check-linter:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Check linter"
          command: echo 'Fake linter check'

workflows:
  version: 2
  quality-checks:
    jobs:
      - install-dependencies
      - check-prettier:
          requires:
            - install-dependencies
      - check-linter:
          requires:
            - install-dependencies
